config/routes.rb
Rails.application.routes.draw do
  resources :userphones, only: [:new, :create, :edit, :update, :index]

  root to: "userphones#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :phones
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/userphones_controller.rb
class UserphonesController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user_phones = UserphoneForm.new
  end

  def create
    @user_phones = UserphoneForm.new userphones_params
    if @user_phones.save
      redirect_to root_path, notice: "User and Phone numbers saved"
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    @user_phones = UserphoneForm.new userphones_params
    if @user_phones.save
      #dumb way of updating
      @user.phones.delete_all
      @user.delete
      @user_phones = UserphoneForm.new userphones_params
      @user_phones.save
      redirect_to root_path, notice: "Username and Phone numbers updated!"
    else
      render :edit
    end
  end

  private

  def userphones_params
    params.require(:user).permit(:username, phones: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SooooooManyPhoneNumbers" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">SooooooManyPhoneNumbers</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/userphones/edit.html.erb
<h1>Update User</h1>

<%= bootstrap_form_for @user, url: userphone_path do |f| %>
  <%= f.text_field :username, name: "user[username]" %>
  <% @user.phones.each do |p| %>
    <%= f.number_field "phones[]", value: p.number, label: "Current Number", name: "user[phones][]" %>
  <% end %>
  <%= f.number_field "phones[]", value: "", label: "Number To Add (numbers only)", name: "user[phones][]" %>
  <%= f.hidden_field :id %>
  <%= f.submit "Update" %>
<% end %>

app/views/userphones/index.html.erb
<h2>Users</h2>
<% @users.each do |u| %>
  <h4><%= u.username %></h4> <%= link_to "Edit", edit_userphone_path(u), class: "btn btn-primary btn-xs" %>
  <ul>
    <% u.phones.each do |p| %>
      <li>
        <%= p.number %>
      </li>
    <% end %>
  </ul>
<% end %>

<h2>New User</h2>
 <%= link_to "New", new_userphone_path, class: "btn btn-primary btn-xs" %>

app/views/userphones/new.html.erb
<h1>New User</h1>

<%= bootstrap_form_for @user_phones, url: userphones_path do |f| %>
  <%= f.text_field :username, name: "user[username]" %>
  <%= f.number_field "phones[]", value: "", label: "Phone 1 (numbers only)", name: "user[phones][]" %>
  <%= f.number_field "phones[]", value: "", label: "Phone 2 (numbers only)", name: "user[phones][]" %>
  <%= f.number_field "phones[]", value: "", label: "Phone 3 (numbers only)", name: "user[phones][]" %>
  <%= f.submit %>
<% end %>